"""access token table

Revision ID: e500a3058cc7
Revises: 4213429790c8
Create Date: 2024-12-01 20:56:55.978983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "e500a3058cc7"
down_revision: Union[str, None] = "4213429790c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesstoken",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("accesstoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accesstoken_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accesstoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accesstoken_created_at"))

    op.drop_table("accesstoken")
    # ### end Alembic commands ###
